blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='blog-home'),
    path('posts/', views.PostListView.as_view(), name='posts'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post-detail')
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.portfolio, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    banner = models.ImageField(upload_to='images/post_banners/')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', args=[self.id])

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .models import Post
import markdown

# Create your views here.
class PostListView(ListView):
    model = Post
    template_name = 'blog/blog-home.html'
    context_object_name = 'posts'


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post-detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        print('Context', context)
        print(context['post'].body)
        context['body'] = markdown.markdown(context['post'].body, extensions=['fenced_code', 'sane_lists'])
        return context

portfolio/views.py
from django.shortcuts import render
from blog.models import Post

def portfolio(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(request, 'index.html', context)

templates/blog/blog-home.html
{% extends 'layout.html' %}
{% load static %}

{% block main %}
     <!--==================== HEADER ====================-->
    <header class="header" id="header">
        <nav class="nav container2">
            <a href="{% url 'blog:blog-home' %}" class="nav__logo">Blog</a>

            <div class="nav__menu" id="nav-menu">
                <ul class="nav__list grid">
                    <li class="nav__item">
                        <a href="{% url 'blog:posts' %}" class="nav__link  active-link">
                            <i class="uil uil-estate nav__icon"></i>All posts
                        </a>
                    </li>
                    <li class="nav__item">
                        <a href="{% url 'home' %}" class="nav__link">
                            <i class="uil uil-file-alt nav__icon"></i>Portfolio
                        </a>
                    </li>
                </ul>

                <i class="uil uil-times nav__close" id="nav-close"></i>
            </div>

            <div class="nav__btns">
                <!-- Theme change button -->
                <i class="uil uil-moon change-theme" id="theme-button"></i>

                <div class="nav__toggle" id="nav-toggle">
                    <i class="uil uil-apps"></i>
                </div>
            </div>
        </nav>
    </header>

    <!--==================== MAIN ====================-->
    <main class="main">

        <section class="section">
             <h2 class="section__title">Blog</h2>
            <span class="section__subtitle">Share my knowledge and experience</span>
            <div class="blog-page-wrapper grid container2">
                {% for post in posts %}
                <a class="blog-container" href="{{ post.get_absolute_url }}">
                    <div class="blog__banner">
                        <img src="{{ post.banner.url }}" alt="">
                    </div>
                    <p class="blog__name line-clamp-1">{{ post.title }}</p>
                    <div class="qualification__calendar">
                        <i class="uil uil-calendar-alt"></i>
                        {{ post.date_posted }}
                    </div>
                    <div class="blog__content">
                        <p class="line-clamp-5">{{ post.body }}</p>
                    </div>
                </a>
                {% endfor %}
            </div>
        </section>

    </main>


{% endblock %}

templates/blog/post-detail.html
{% extends 'layout.html' %}
{% load static %}

{% block main %}
     <!--==================== HEADER ====================-->
    <header class="header" id="header">
        <nav class="nav container2">
            <a href="{% url 'blog:blog-home' %}" class="nav__logo">Blog</a>

            <div class="nav__menu" id="nav-menu">
                <ul class="nav__list grid">
                    <li class="nav__item">
                        <a href="{% url 'blog:posts' %}" class="nav__link  active-link">
                            <i class="uil uil-estate nav__icon"></i>All posts
                        </a>
                    </li>
                    <li class="nav__item">
                        <a href="{% url 'home' %}" class="nav__link">
                            <i class="uil uil-file-alt nav__icon"></i>Portfolio
                        </a>
                    </li>
                </ul>

                <i class="uil uil-times nav__close" id="nav-close"></i>
            </div>

            <div class="nav__btns">
                <!-- Theme change button -->
                <i class="uil uil-moon change-theme" id="theme-button"></i>

                <div class="nav__toggle" id="nav-toggle">
                    <i class="uil uil-apps"></i>
                </div>
            </div>
        </nav>
    </header>

    <!--==================== MAIN ====================-->
    <main class="main">
        <section class="section">

            <div class="blog-page-wrapper container2">




                <div class="post__banner">
                    <img src="{{ post.banner.url }}" alt="">
                </div>

                <h1 class="blog__title">{{ post.title }}</h1>
                <div class="qualification__calendar">
                    <i class="uil uil-calendar-alt"></i>
                   {{ post.date_posted }}
                </div>

                <div class="blog__content__detail">
                    {{ body | safe }}
                </div>
            </div>


        </section>

    </main>


{% endblock %}

templates/layout.html
<!DOCTYPE html>
    {% load static %}
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Pyae Phyo Kyaw | Portfolio</title>

        <!--==================== UNICONS ====================-->
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">

        <!--==================== SWIPER CSS ===================-->
        <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}">

        <!--==================== CUSTOM CSS ====================-->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <!--==================== MAIN BLOCK ====================-->
        {% block main %}
        {% endblock %}

        <!--==================== SWIPER JS ====================-->
        <script src="{% static 'js/swiper-bundle.min.js' %}"></script>

        <!--==================== MAIN JS ====================-->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>